# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-02 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_asiento', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comprador', models.TextField()),
                ('documento_identidad', models.TextField()),
                ('numero_factura', models.TextField()),
                ('numero_asiento', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.TextField()),
                ('max_asientos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.TextField()),
                ('documento_identidad', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_horario', models.TextField()),
                ('hora_salida', models.TextField()),
                ('hora_llegada', models.TextField()),
                ('dia', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Trayecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_trayecto', models.TextField()),
                ('origen', models.TextField()),
                ('destino', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_viaje', models.TextField()),
                ('fecha', models.DateField()),
                ('puestos_disponibles', models.IntegerField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Bus')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Horario')),
                ('trayecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Trayecto')),
            ],
        ),
        migrations.AddField(
            model_name='bus',
            name='chofer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Chofer'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='viaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Viaje'),
        ),
        migrations.AddField(
            model_name='asiento',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Bus'),
        ),
    ]
